[project]
name = "pythonproject17"
version = "0.1.0"
description = "Referral System with Phone Authentication"
authors = [
    {name = "fantasticlion", email = "den20020805@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "django>=5.1.2,<6.0.0",
    "djangorestframework>=3.15.1,<4.0.0",
    "psycopg2-binary>=2.9.10,<3.0.0",
    "python-dotenv>=1.0.0,<2.0.0",
    "dj-database-url>=2.1.0,<3.0.0",
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
pytest = "^8.0.0"
pytest-django = "^4.8.0"
coverage = "^7.0.0"
pytest-cov = "^4.0.0"

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "config.settings"
python_files = ["tests.py", "test_*.py", "*_tests.py"]
addopts = "--reuse-db"

[tool.coverage.run]
source = ["users"]
omit = ["*/migrations/*", "*/tests/*"]